/*CREATE TABLE `Person` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL DEFAULT '',
  `country` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
commit;
*/

CREATE TABLE IF NOT EXISTS Person (
  id INTEGER(11) unsigned NOT NULL AUTO_INCREMENT,
  name varchar(20) NOT NULL DEFAULT '',
  country varchar(20) DEFAULT NULL,
  PRIMARY KEY (id)
)

/*
CREATE TABLE IF NOT EXISTS t_user
(user_id integer GENERATED BY DEFAULT AS IDENTITY,
user_birth date NOT NULL,
created_at TIMESTAMP NOT NULL,
user_email varchar(64) NOT NULL,
user_name varchar(255) NOT NULL,
user_password varchar(255) NOT NULL,
updated_at TIMESTAMP NOT NULL,
VERSION integer NOT NULL,
PRIMARY KEY (user_id))
ALTER TABLE t_user ADD CONSTRAINT uk_user_email UNIQUE (user_email)*/
